[book]
authors = ["Normand Gosselin"]
language = "fr"
multilingual = false
src = "src"
title = "Guide sanitaire pour les ensembles musicaux"
description = """
Guide sanitaire pour les ensembles musicaux écrit par Normand Gosselin,
enseignant, compositeur et organisateur d'événement musical et la Fédération des
Harmonies et Orchestres Symphoniques du Québec (FAMEQ), pour les membres de la
FAMEQ et de la Fédération des Associations de Musiciens Éducateurs du Québec.
Version élaborée selon les encadrements du 2 juillet 2020."""

[output.html]
additional-css = ["src/css/custom.css"]
